#4 консоль запросов Active record query interface
Psyker-h/test_guru pull request #3
Opened 2021-11-21 18:37 UTC by Psyker-h

2021-11-22 04:40 UTC, TimmyMT commented
Где описание?

2021-11-22 04:55 UTC, TimmyMT requested changes

2021-11-22 04:55 UTC, TimmyMT commented on app/models/test.rb
> +  def sort_by_descr(category)
Это должен быть мето класса. Он не должен вызываться у объекта

2021-11-22 04:55 UTC, TimmyMT commented on app/models/test.rb
> +    Test.order(title: :desc).where("title = ?", category)
Ты проверял? Это работает?

2021-11-22 04:55 UTC, TimmyMT commented on app/models/user.rb
> +  def self.all_test(lvl)
В задании речь идёт о тестах, которые проходил пользователь а это значит что метод должен вызываться у объекта.

2021-11-22 04:55 UTC, TimmyMT commented on app/models/user.rb
> +    Test.all.where("level = ?", lvl)
Метод должен возвращать только те тесты которые проходил пользователь.
Подсказываю: Нужно создать модель Result которая будет привязана к user_id и test_id
Затем нужна выборка тестов которые из results
Для этого нужно использовать joins
http://rusrails.ru/active-record-query-interface#soedinenie-odinochnoy-svyazi

2021-11-22 04:55 UTC, TimmyMT commented on db/seeds.rb
> +Test.create(title: 'Java', level: 2)
```suggestion
Test.create!([
  {title: 'Ruby', level: 1}, {title: 'PHP', level: 1}, {title: 'Java', level: 2}
])
```

2021-11-22 04:55 UTC, TimmyMT commented on db/seeds.rb
> +Test.create(title: 'Java', level: 2)
С другими также

2021-11-22 13:28 UTC, Psyker-h commented on app/models/user.rb
> +  def self.all_test(lvl)
Сделано

2021-11-23 18:41 UTC, TimmyMT approved these changes

2021-11-25 15:30 UTC, merged